### PR TITLE
MVP: Create standalone irc bot

### PR DESCRIPTION
**Pull request by glensc**
The standalone irc bot will implement same functionality present in eventum 3.4.1 release.

- uses xmlrpc methods to communicate with eventum: https://github.com/eventum/eventum/pull/369

<del>It will use xmlrpc to do eventum integration and likely use rabbitmq queue for events.</del>

### CODE REVIEW

**Comment by glensc** [comment]
needs Eventum to validate user status when checking auth: https://github.com/eventum/eventum/pull/369

**Comment by glensc** [comment]
Needs `getClockedInList` api method: eventum/eventum#369

**Comment by glensc** [comment]
@balsdorf what is issue quarantine? how does one set it? i find `Issue::setQuarantine` to be used only for removing quarantine. it's for workflow methods?

**Comment by glensc** [comment]
noticed that in my database, irc bot keeps polling 60k messages continuously...

```

14:29:19 mysql{3}> SELECT count(*)  FROM `irc_notice`  LEFT JOIN `issue` ON iss_id=ino_iss_id  WHERE ino_status='pending';
+----------+
| count(*) |
+----------+
|    61269 |
+----------+
1 row in set (0.23 sec)
```

**Comment by glensc** [comment]
this seems complete with the existing implementation. i was thinking that the bot should have dedicated user and use rpc methods that require higher privileges to act on other users behalf.

**Comment by balsdorf** [comment]
Issue Quarantine was something from the old MySQL AB days. Basically if certain conditions were met (such as a customer having an expired contract) the issue would be quarantined and no one would work on it until they renewed. I don't use it now and with no UI for setting quarantine I can't imagine anyone else does either. It can be removed IMO.

**Comment by glensc** [comment]
https://github.com/eventum/irc-bot/pull/1#issuecomment-385652222

so, added logic change: bot will fetch only projects that are still active and configured to poll. and it will poll each project on it's own, so the distribution would go even.

i'll also think that perhaps need to add `expired` state, because otherwise it will be getting only 50 items which none it marks as done. but i haven't looked my database closely why there are so many 'pending' items in table.

**Pull request merged**
